# -*- coding: utf-8 -*-
"""Assignment_5_DollyJha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18QyiST5lvvBouKJSLli5TZHxqDWpLyNg

# Task 1: Create a Dictionary of Student Marks
- Creates a dictionary with student names as keys and their marks as values.
- Prompts the user to enter a student's name.
- Retrieves and displays the student's marks if the name exists.
- Displays an appropriate message if the student's name is not found in the dictionary.
"""

student_dict = {"Ankita":{34,45,68},"Rahul":{87,75,98},"Vicky":{78,65,67}}
user_name = input("Enter the student's Name: ")
if user_name in student_dict:
    print(f"{user_name}'s marks: {student_dict[user_name]}")
else:
    print("Student not found.")

"""# Task 2: Demonstrate List Slicing
- Creates a list of numbers from 1 to 10.
- Extracts the first five elements using list slicing.
- Reverses the extracted list.
- Displays both the original extracted list and the reversed list.
"""

no_list = list(range(1,11))
print(f"Original list : {no_list}")
print(f"First five elements of the list : {no_list[0:5]}")
other_list = no_list[0:5]
print(f"Reversed list : {other_list[::-1]}")